### ISSUE TITLE
Provide error feed back when problem post fails

### ISSUE THREAD

**Issue by Josiah-DuBose** [bike-md/bike_md#1]
In script.js there is a function called postProblem. There is currently no error checking or feedback in the event that the ajax call fails. Please check if all the required fields are filled in, alert the user if the call fails or succeeds, and provide a reason if it fails

**Comment by mvellasco** [comment]
I'm working on it. I'll submit a PR as soon as I am done. If you can, please assign me to this issue.

**Comment by mvellasco** [comment]
I just sent a PR for review. Also, I'd like to be a part of the project as a contributor so I can do some more, I have some ideas such as adding tests, refactoring views, etc, and I'd love to help out in any way I can.

**Comment by mvellasco** [comment]
Hello @Josiah-DuBose, how do you do? I saw that you didn't close the issue, is there anything else to be done?
